# Generated by Django 4.1.6 on 2023-02-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=255)),
                ('service_photo', models.ImageField(upload_to='photos')),
                ('service_photo_1', models.ImageField(blank=True, upload_to='photos')),
                ('service_photo_2', models.ImageField(blank=True, upload_to='photos')),
                ('service_prise_from', models.IntegerField()),
                ('service_prise_to', models.IntegerField()),
                ('service_description', models.TextField(max_length=2000)),
            ],
        ),
    ]
