# Generated by Django 4.1.6 on 2023-02-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalex', '0003_alter_service_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_position', models.CharField(max_length=30)),
                ('team_photo', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
