# Generated by Django 4.1.6 on 2023-02-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalex', '0006_social_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='schedule',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
