# Generated by Django 4.1.6 on 2023-02-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalex', '0008_sociallink_delete_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
