# Generated by Django 4.1.6 on 2023-03-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalex', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_prise_flag',
            field=models.BooleanField(default=False),
        ),
    ]
